version: '3.1'

services:

  walletkit:
    image: waltid/walletkit:latest  # backend docker image
    command:
      - run
    environment:
      WALTID_DATA_ROOT: /waltid-walletkit/data-root
      WALTID_WALLET_BACKEND_BIND_ADDRESS: 0.0.0.0
      WALTID_WALLET_BACKEND_PORT: "7000"
      # EXTERNAL_HOSTNAME: host.docker.internal
      EXTERNAL_HOSTNAME: 0.0.0.0
    volumes:
      - ./walletkit:/waltid-walletkit/data-root # data store volume incl. config files.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 7000:7000

  wallet-backend:
    image: waltid/wallet-backend:latest
    volumes:
      - ./wallet-backend/config:/waltid-web-wallet/config
      - ./wallet-backend/walt.yaml:/waltid-web-wallet/walt.yaml
    ports:
      - 4545:4545

  wallet-frontend:
    image: waltid/wallet-frontend:latest
    environment:
      NUXT_PUBLIC_ISSUER_URL: "http://0.0.0.0:8002"
    ports:
      - 3001:3000

  issuer-portal:
    image: waltid/ssikit-issuer-portal:latest
    ports:
      - 8002:80

  verifier-portal:
    image: waltid/ssikit-verifier-portal:latest
    ports:
      - 9001:80

  # ingress:
  #   image: nginx:1.15.10-alpine
  #   ports:
  #     - 3001:3000
  #     - 8002:8000
  #     - 9001:9000
  #   volumes:
  #     - ./ingress.conf:/etc/nginx/conf.d/default.conf # API gateway configuration

  vault:
    image: docker.io/bitnami/vault:1
    ports:
      - "127.0.0.1:8200:8200"
    volumes:
      - ./file:/vault/file:rw
      - ./config:/vault/config:rw
    entrypoint: vault server -config=/vault/config/vault.json